# hugo (https://gohugo.io) configuration

title = "BenTheElder"
copyright = "Copyright © 2015-{year} Benjamin Elder."
baseURL = "https://elder.dev"
languageCode = "en-us"

# these are defaults, but let's be explicit
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
staticDir = ["static"]
layoutDir = "layouts"

ignore = ["^README.md$"]

enableGitInfo = true

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=inline"

# we don't use thse
disableKinds = ["taxonomy","taxonomyTerm"]

# build draft posts
buildDrafts = true

# allow inline html
[markup.goldmark.renderer]
unsafe= true